apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-redis
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0ce61e1d46244fdf6

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-redis
spec:
  volumeName: efs-pv-redis
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi