apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0c804e84331cdf4df

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-postgres
spec:
  volumeName: efs-pv-postgres
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi


