apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-rasax
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0857e16ac3bc3d186

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-rasax
spec:
  volumeName: efs-pv-rasax
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi
