apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-rabbitmq
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0f45a07a4e4db237f

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-rabbitmq
spec:
  volumeName: efs-pv-rabbitmq
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi